name: metric

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '15 16 * * *' # every 00:15 +08:00
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # plugin_languages: yes
          plugin_habits: yes
          plugin_lines: yes
          # plugin_traffic: yes
